from __future__ import annotations

from dataclasses import dataclass


@dataclass(slots=True)
class DeviceInfo:
    identity: str = ""
    version: str = ""
    uptime: str = ""
    cpu_load: str = ""
    board_name: str = ""
    platform: str = ""
    architecture: str = ""
    total_memory: str = ""
    free_memory: str = ""
    total_hdd: str = ""
    free_hdd: str = ""
    license: str = ""
    current_firmware: str = ""
    upgrade_firmware: str = ""
    interface_count: str = ""
    mac_address: str = ""
    uplink_interface: str = ""
    uplink_mac: str = ""
    neighbor_identity: str = ""
    neighbor_address: str = ""
    neighbor_interface: str = ""
    neighbor_mac: str = ""
    installed_packages: str = ""
    ospf_instance_count: str = ""
    ospf_neighbor_count: str = ""
    ospf_instances: str = ""
    bridge_count: str = ""
    bridge_port_count: str = ""
    bridge_names: str = ""
    scheduler_count: str = ""
    scheduler_names: str = ""
    dhcp_server_count: str = ""
    dhcp_client_count: str = ""
    ssh_port_value: str = ""
    winbox_port_value: str = ""
    firewall_filter_count: str = ""
    firewall_nat_count: str = ""
    route_count: str = ""
    default_route_count: str = ""
    vlan_count: str = ""
    vlan_names: str = ""
    radius_count: str = ""
    watchdog_enabled: str = ""
