"""Implementation details for sot __init__."""

from .adapters import device_from_audit_result, device_from_device_info
from .contracts import (
    CollectorPlugin,
    CorrelationPlugin,
    NormalizerPlugin,
    RecommendationRule,
    RemediationPlanner,
    RiskRule,
    TopologyStage,
)
from .domain import (
    BroadcastDomain,
    Bridge,
    Device,
    Interface,
    Neighbor,
    NetworkSnapshot,
    NetworkSegment,
    OSPFNeighbor,
    Optic,
    Recommendation,
    RemediationPlan,
    Risk,
    Ring,
    Route,
    SnapshotMetadata,
    TopologyLink,
    VLAN,
    VLANPropagation,
    WirelessLink,
)
from .pipeline import PipelineContext, RawCommandPayload, StageResult
from .repositories import (
    DeviceRepository,
    EvidenceRepository,
    RemediationRepository,
    RiskRepository,
    SnapshotRepository,
    TopologyRepository,
)

__all__ = [
    "BroadcastDomain",
    "Bridge",
    "CollectorPlugin",
    "CorrelationPlugin",
    "device_from_audit_result",
    "device_from_device_info",
    "Device",
    "DeviceRepository",
    "EvidenceRepository",
    "Interface",
    "Neighbor",
    "NetworkSegment",
    "NetworkSnapshot",
    "NormalizerPlugin",
    "OSPFNeighbor",
    "Optic",
    "PipelineContext",
    "RawCommandPayload",
    "Recommendation",
    "RecommendationRule",
    "RemediationPlan",
    "RemediationPlanner",
    "RemediationRepository",
    "Ring",
    "Risk",
    "RiskRepository",
    "RiskRule",
    "Route",
    "SnapshotMetadata",
    "SnapshotRepository",
    "StageResult",
    "TopologyLink",
    "TopologyRepository",
    "TopologyStage",
    "VLAN",
    "VLANPropagation",
    "WirelessLink",
]
