"""Implementation details for config."""

from __future__ import annotations

from mikrotik_audit.config_parts import (
    FALSE_VALUES,
    TRUE_VALUES,
    AppConfig,
    AuditConfig,
    BackupConfig,
    ComplianceConfig,
    CredentialConfig,
    FirmwareConfig,
    GatewayAuthConfig,
    GoogleConfig,
    MikroTikAuthConfig,
    NTPConfig,
    PHPIPAMConfig,
    RadiusConfig,
    RemediationConfig,
    ReportConfig,
    RuntimeConfig,
    SchedulerConfig,
    SchedulerRule,
    ServiceConfig,
    WatchdogConfig,
    as_bool,
    as_dict,
    as_list,
    env_bool,
    env_csv,
    env_int,
    env_optional_path,
    env_raw,
    env_str,
    format_hms,
    load_yaml_file,
    normalize_inventory_data,
    parse_hms,
    resolve_project_path,
)

__all__ = [
    "AppConfig",
    "AuditConfig",
    "BackupConfig",
    "ComplianceConfig",
    "CredentialConfig",
    "FALSE_VALUES",
    "FirmwareConfig",
    "GatewayAuthConfig",
    "GoogleConfig",
    "MikroTikAuthConfig",
    "NTPConfig",
    "PHPIPAMConfig",
    "RadiusConfig",
    "RemediationConfig",
    "ReportConfig",
    "RuntimeConfig",
    "SchedulerConfig",
    "SchedulerRule",
    "ServiceConfig",
    "TRUE_VALUES",
    "WatchdogConfig",
    "as_bool",
    "as_dict",
    "as_list",
    "env_bool",
    "env_csv",
    "env_int",
    "env_optional_path",
    "env_raw",
    "env_str",
    "format_hms",
    "load_yaml_file",
    "normalize_inventory_data",
    "parse_hms",
    "resolve_project_path",
]

settings = AppConfig.from_env()
